In [1]:
#1. Why does this feature selection with chi2 fail?
from sklearn.feature_selection import SelectKBest, chi2

X = [[-1, 2, 3], [4, 0, -6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)


ValueError: Input X must be non-negative.

In [3]:
# current issues => presence of negative values
#   chi2 requires non negative values
#
# Solution:
#   scale the features from 0 to 1.

from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler

X = [[-1, 2, 3], [4, 0, -6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(X)
selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(x_scaled, y)
print(X_new)

[[0.25 0.6 ]
 [0.   0.  ]
 [1.   1.  ]
 [0.25 0.6 ]]


In [ ]:
#2.
from sklearn.metrics.pairwise import cosine_similarity

# Error: strings instead of numerical features
user1 = ['action', 'comedy', 'romance']
user2 = ['action', 'thriller', 'comedy']

similarity = cosine_similarity([user1], [user2])

In [9]:
# current issues => similarity requires numeric but categorical data given
# solution:
#       encode the data

from sklearn.preprocessing import MultiLabelBinarizer

encoded = MultiLabelBinarizer().fit_transform([user1, user2])
similarity = cosine_similarity([encoded[0]], [encoded[1]])
print(similarity)

[[0.66666667]]


In [ ]:
#3.
from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
pca = PCA(n_components=5)  # more components than features
X_new = pca.fit_transform(X)


In [11]:
# current issues => more components specified than features available
# solution => reduce the n_components
from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
pca = PCA(n_components=2)  # more components than features
X_new = pca.fit_transform(X)
print(X_new)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [ ]:
#4.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])

similarity = cosine_similarity(ratings)


In [12]:
# current issues => Null values present in dataset. 
# solution => fill NaN values

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])
ratings = np.nan_to_num(ratings)
similarity = cosine_similarity(ratings)
print(similarity)

[[1.         0.68599434]
 [0.68599434 1.        ]]


In [ ]:
#5.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

selector = RFE(estimator=LogisticRegression(), n_features_to_select=5)
selector.fit(X, y)  

# Error: X and y not defined

In [ ]:
# 6.

from sklearn.metrics.pairwise import cosine_similarity

items = ["action movie", "romantic comedy", "sci-fi thriller"]
similarity = cosine_similarity([items[0]], [items[1]])

In [16]:
# current issues => texts are passed as argument for cosine similarity
# solution:
#       * encode the categorical data. In this case the data is not just categorical, it is a text.
#       * encoding for texts --> TF-IDF Vectorizer (Term Frequency Inverse Document Frequency)
#       * converts text to vectors
#       * TF (Term Frequency) → how often a word appears in a document
#       * IDF (Inverse Document Frequency) → how rare or important that word is across all documents


from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

items = ["action movie", "romantic comedy", "sci-fi thriller"]

vectorizer = TfidfVectorizer()
items_vectorized = vectorizer.fit_transform(items)
print(items_vectorized)

# similarity between 'action movie' & 'romantic comedy'
similarity = cosine_similarity(items_vectorized[:1], items_vectorized[1:2])
print("similarity\n", similarity)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (3, 7)>
  Coords	Values
  (0, 0)	0.7071067811865476
  (0, 3)	0.7071067811865476
  (1, 4)	0.7071067811865476
  (1, 1)	0.7071067811865476
  (2, 5)	0.5773502691896257
  (2, 2)	0.5773502691896257
  (2, 6)	0.5773502691896257
similarity
 [[0.]]


In [ ]:
#7.
from sklearn.feature_selection import SelectKBest, f_classif

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1]  # Error: mismatched dimensions
selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)


In [18]:
# current issues => arguments length mismatch (X = 3, y=2)
from sklearn.feature_selection import SelectKBest, f_classif

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1, 2]  # Error: mismatched dimensions
selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)
print(X_new)

[[2]
 [4]
 [6]]


d:\AI_course\set questions\4030610-4AdvancedMLWeek81to10\.venv\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:107: RuntimeWarning: invalid value encountered in divide
  msw = sswn / float(dfwn)


In [19]:
# 8.
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ratings = np.array([5, 4, 3])

# cosine_similarity(ratings, ratings)  #! ERROR: cosine similarity expects 2D array.

similarity = cosine_similarity([ratings], [ratings])
print(similarity)

[[1.]]


In [47]:
#9.
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2

X = [[1, 2], [3, None], [4, 5]]
y = [0, 1, 0]

X = np.nan_to_num(np.array(X, dtype=float))
print(X)

#! error -> NaN values present in X
# solution -> fill missing values

pipeline = Pipeline([
    ('select', SelectKBest(score_func=chi2, k=1))
])

pipeline.fit(X, y)



[[1. 2.]
 [3. 0.]
 [4. 5.]]


,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('select', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"score_func score_func: callable, default=f_classifFunction taking two arrays X and y, and returning a pair of arrays(scores, pvalues) or a single array with scores.Default is f_classif (see below ""See Also""). The default function onlyworks with classification tasks... versionadded:: 0.18",<function chi...00274F629E200>
,"k k: int or ""all"", default=10Number of top features to select.The ""all"" option bypasses selection, for use in a parameter search.",1


In [ ]:
#10.
from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, chi2

X = csr_matrix([[0, -1, 3], [0, 2, 1], [3, -1, 0]]) #! ERROR: negative values present for chi2
y = [0, 1, 0]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)


In [53]:
# current issues -> chi2 accepts only non negative values

from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, chi2

X = csr_matrix([[0, -1, 3], [0, 2, 1], [3, -1, 0]])
y = [0, 1, 0]

#! MinMax scaler doesnt support sparse matrix (CSR).
#! MaxAbsScaler support CSR but contains non negative values (-1,1)

# Hence clipping negative values to 0
X.data[X.data < 0] = 0

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)
print(X_new)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (3, 2)>
  Coords	Values
  (0, 1)	0
  (1, 1)	2
  (2, 0)	3
  (2, 1)	0
