In [ ]:
#1.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]

rfe = RFE(estimator=LogisticRegression(), n_features_to_select=1)
X_new = rfe.fit_transform(X, y)
print(X_new)

# adding additional samples improve efficiency

[[2]
 [4]
 [6]]


In [4]:
#2.
from sklearn.feature_selection import VarianceThreshold

X = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
selector = VarianceThreshold(threshold=0.1)

# X has only 0's and hence no variance

X = [[0, 1, 0], [0, 2, 1], [1, 1, 0]]
X_new = selector.fit_transform(X)
print(X_new)

[[0 1 0]
 [0 2 1]
 [1 1 0]]


In [5]:
# 3.
from sklearn.metrics.pairwise import cosine_similarity

# data = [[5, 0, 3], [0, 0, 0]]
# similarity = cosine_similarity(data)

# data[1] contains all 0's hence undefined fr zero vectors
data = [[5, 0, 3], [0, 1, 2]]
similarity = cosine_similarity(data)
print(similarity)

[[1.         0.46017899]
 [0.46017899 1.        ]]


In [11]:
# 4.
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]
selector = SelectFromModel(DecisionTreeClassifier(), threshold="mean")
X_new = selector.fit_transform(X, y)
print(X_new)

## adding additional samples improve efficiency

X1 = [[1, 2], [3, 4], [5, 6], [7, 8], [2, 3]]
y1 = [1, 0, 1, 0, 1]
X_new1 = selector.fit_transform(X1, y1)
print("X_new1: \n", X_new1)

[[2]
 [4]
 [6]]
X_new1: 
 [[1]
 [3]
 [5]
 [7]
 [2]]


In [14]:
#5.
import pandas as pd
data = pd.DataFrame({
    'user': ['A', 'B', 'A'],
    'item': ['I1', 'I2', 'I2'],
    'rate': [5, 4, 3]
})
# pivot = data.pivot(index='user', columns='item', values='rating') #! wrong column name for 'values'

# correct usage
pivot = data.pivot(index='user', columns='item', values='rate') 
pivot

item,I1,I2
user,,
A,5.0,3.0
B,NaN,4.0


In [15]:
#6.
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2], [3, 4]])  

#pca = PCA(n_components=3)       #! ERROR: component size greater than total features
pca = PCA(n_components=1)

X_new = pca.fit_transform(X)
print(X_new)



[[-1.41421356]
 [ 1.41421356]]


In [17]:
#7.
'''ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})
sim = cosine_similarity(ratings.T)'''

ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})
# ratings has null values. 
ratings = ratings.fillna(0)
sim = cosine_similarity(ratings.T)
print(similarity)


[[1.         0.46017899]
 [0.46017899 1.        ]]


In [24]:
# 8.
import numpy as np

user_vec = np.array([1, 2])
item_vec = np.array([0.5, 1.0])
score = np.dot(user_vec, item_vec) 
print("Predicted Score:", score)

Predicted Score: 2.5


In [25]:
#9.
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors()
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=2)
print(indices)


[[0 2]]


In [26]:

#10.
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors(metric='hamming')
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=2)
print("Neighbors (indices):", indices)


Neighbors (indices): [[0 2]]


In [28]:
#11.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

a = np.array([1, 0, 1])
b = np.array([0, 1, 1])

#sim = cosine_similarity(a, b) #! ERROR: COSINE_SIMILARITY REQUIRES 2D ARRAY
sim = cosine_similarity([a], [b])
print("Similarity:", sim)

Similarity: [[0.5]]
